language: node_js
node_js:
  - "11"

branches:
  only:
    - source

install:
  - git clone https://github.com/Hadron67/Noteblog.git
  - cd Noteblog
  - npm i
  - cd ..
  - npm i rollup -g
  - npm i terser -g
  - cd theme/default
  - rollup -c
  - terser dist/main.js --compress --mangle -o dist/main.js
  - cd ../..

script:
  - mkdir dist
  - ./Noteblog/cli/noteblog g

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  target-branch: master
  on:
    branch: source